### PR TITLE
Voxelize

### PR DESCRIPTION
**Pull request by RArbore**
Convert .obj models to SVDAG, with uv mapped textures.

Make chunk request more precise.

### CODE REVIEW

**Comment by Jebbly** [comment]
I'm having some trouble loading both sponza and dragon (acquired from [here](https://casual-effects.com/data/)) with the following outputs:

```
C:\Users\JeffL\Desktop\Personal-Projects\illinois-voxel-sandbox\build\drivers\Debug>convert_model.exe sponza.obj 128                                                                                                                 
sponza.obj 128
PANIC: Both `d` and `Tr` parameters defined for "leaf". Use the value of `d` for dissolve (line 8 in .mtl.)                                                                                                                          
Both `d` and `Tr` parameters defined for "vase_round". Use the value of `d` for dissolve (line 24 in .mtl.)                                                                                                                          
Both `d` and `Tr` parameters defined for "Material__57". Use the value of `d` for dissolve (line 39 in .mtl.)                                                                                                                        
Both `d` and `Tr` parameters defined for "Material__298". Use the value of `d` for dissolve (line 54 in .mtl.)                                                                                                                       
Both `d` and `Tr` parameters defined for "bricks". Use the value of `d` for dissolve (line 70 in .mtl.)                                                                                                                              
Both `d` and `Tr` parameters defined for "arch". Use the value of `d` for dissolve (line 86 in .mtl.)                                                                                                                                
Both `d` and `Tr` parameters defined for "ceiling". Use the value of `d` for dissolve (line 100 in .mtl.)                                                                                                                            
Both `d` and `Tr` parameters defined for "column_a". Use the value of `d` for dissolve (line 114 in .mtl.)                                                                                                                           
Both `d` and `Tr` parameters defined for "floor". Use the value of `d` for dissolve (line 129 in .mtl.)                                                                                                                              
Both `d` and `Tr` parameters defined for "column_c". Use the value of `d` for dissolve (line 144 in .mtl.)                                                                                                                           
Both `d` and `Tr` parameters defined for "details". Use the value of `d` for dissolve (line 159 in .mtl.)                                                                                                                            
Both `d` and `Tr` parameters defined for "column_b". Use the value of `d` for dissolve (line 173 in .mtl.)                                                                                                                           
Both `d` and `Tr` parameters defined for "Material__47". Use the value of `d` for dissolve (line 188 in .mtl.)                                                                                                                       
Both `d` and `Tr` parameters defined for "flagpole". Use the value of `d` for dissolve (line 200 in .mtl.)                                                                                                                           
Both `d` and `Tr` parameters defined for "fabric_e". Use the value of `d` for dissolve (line 214 in .mtl.)                                                                                                                           
Both `d` and `Tr` parameters defined for "fabric_d". Use the value of `d` for dissolve (line 228 in .mtl.)                                                                                                                           
Both `d` and `Tr` parameters defined for "fabric_a". Use the value of `d` for dissolve (line 242 in .mtl.)                                                                                                                           
Both `d` and `Tr` parameters defined for "fabric_g". Use the value of `d` for dissolve (line 256 in .mtl.)                                                                                                                           
Both `d` and `Tr` parameters defined for "fabric_c". Use the value of `d` for dissolve (line 270 in .mtl.)                                                                                                                           
Both `d` and `Tr` parameters defined for "fabric_f". Use the value of `d` for dissolve (line 284 in .mtl.)                                                                                                                           
Both `d` and `Tr` parameters defined for "chain". Use the value of `d` for dissolve (line 298 in .mtl.)                                                                                                                              
Both `d` and `Tr` parameters defined for "vase_hanging". Use the value of `d` for dissolve (line 314 in .mtl.)                                                                                                                       
Both `d` and `Tr` parameters defined for "vase". Use the value of `d` for dissolve (line 329 in .mtl.)                                                                                                                               
Both `d` and `Tr` parameters defined for "Material__25". Use the value of `d` for dissolve (line 344 in .mtl.)                                                                                                                       
Both `d` and `Tr` parameters defined for "roof". Use the value of `d` for dissolve (line 359 in .mtl.)

Occurred in C:\Users\JeffL\Desktop\Personal-Projects\illinois-voxel-sandbox\voxels\Voxelize.cpp at line 108.
```

Do we need that assertion for no warnings at all? I get a bit further with the dragon but the program aborts at some point:

```
C:\Users\JeffL\Desktop\Personal-Projects\illinois-voxel-sandbox\build\drivers\Debug>convert_model.exe dragon.obj 128                                                                                                                 
dragon.obj 128                                                                                                                                                                                                                       
Bottom corner: (-0.23978, -0.282958, -0.472247)                                                                                                                                                                                      
Top corner: (0.207395, 0.422022, 0.527753)                                                                                                                                                                                           
Chunk size: (1, 1, 1)                                                                                                                                                                                                                
871306 triangles 
```

Am I running or setting this up incorrectly? Or could this be a Windows specific issue?

**Comment by RArbore** [comment]
For the first issue, we could def remove that assertion.

For the second issue, my guess is that the dragon doesn't have associated textures to UV map? Let me push w/o the assertion for sponza. Take a look at the projected voxelization size before letting it too long - I would recommend voxelizing to a resolution of (200-300)^3 ish if you don't want to wait too long.

**Comment by Jebbly** [comment]
Yeah, it looks like it was because the dragon had no UVs, so I just pushed a change to fix that. Also includes some white space changes to all spaces. The conversion now works, but running it at camera location (0, 0, -5) shows this:
image

Sponza now gets further but still doesn't finish or write out the DAG - looking further into it.

**Comment by Jebbly** [comment]
Something might be up with tinyobjloader for sponza - the sponza.obj comes with a commented number of triangles per mesh, but they don't match up with the number of triangles reported by tinyobjloader. Blender seems to load in the sponza geometry just fine, so not sure what's going on.

**Comment by RArbore** [comment]
One issue with sponza is because it uses backslashes in the .mtl for texture filepaths... There are also some materials without textures, which were not handled properly before. Sponza works now.

**Comment by RArbore** [comment]
Dragon runs fine on my machine. Make sure to adjust the voxelization size based on the projected voxel size of the model, which gets printed at the beginning of the conversion process. Might go AWOL if the size of one voxel is larger than the whole model.

**Comment by Jebbly** [comment]
Testing it with correct voxel sizes now works for me - we may want to adjust the documentation to:
```
"Must provide a resolution to voxelize at" -> "Must provide a voxel size to voxelize at"
```
Resolution sounds a bit like what the total dimensions should be, which is what I was confused by.

Otherwise LGTM, do we want to fix the vertex colors in this PR?

**Comment by RArbore** [comment]
Yea, I think so. Will do that soon.

**Comment by Jebbly** [comment]
So looking at the issue more - I think the main issue is actually that one of the textures (sponza_arch_diff.png) is messed up. I've done a bit of a hacky fix here by fixing the texture, and vertex colors aren't a main feature supported by the [OBJ file format], so I'm not sure if this is a heavy priority anymore. Here is the fixed Sponza:

https://drive.google.com/file/d/1m4LIrwBkq6pA1q4CFqm2UijgOX3T2EtT/view?usp=sharing

This is just copying the bottom of the texture to the top, but since the voxelization doesn't preserve texture detail entirely, it seems to work decently.

**Comment by RArbore** [comment]
Yea, I've noticed that a couple of the models from that .obj library are a little screwed up. The white oak tree model has a couple triangles with 0 area, so texture mapping used to fail spectacularly. I noticed that same texture issue in the San Miguel model.

**Review by Jebbly — APPROVED** [review]
LGTM - would be good if someone else could also take a pass over the code after I did my merges; accidentally messed a few things up during merging that I fixed manually.

**Pull request merged**
