### PR TITLE
Add Scene Description Format

### LINKED ISSUE #23: Add Scene Description Format
We currently have to create a new target for each new scene. It would be more efficient if we used a scene description format (e.g. YAML, JSON, etc) so that we would only need to build one executable and run with different scenes.

### PR DESCRIPTION
**Pull request by Jebbly**
Introduces a new driver, ``scene_viewer.cpp``, to load scenes directly. This uses a JSON library to read scenes directly without the need to recompile executables. Samples are provided in the ``samples/`` directory.

Note that existing executables are still kept (including the Sponza executable). The Sponza executable can be replaced once the sample has been appropriately configured to mimic the same setup. Similarly, the ``island`` and ``benchmark_graphics`` can also be replaced since they don't introduce any new functionality specifically, although we may want to use a script to generate the scripts (writing out the JSON would take a while). 

Alternatively, we can provide the JSON functionality from ``scene_viewer.cpp`` as a library, so ``island`` and ``benchmark_graphics`` could configure the JSON scene directly without needing to worry about managing the chunk manager, scene, etc. manually.

To-dos (not urgent):
- For models, the dimensions can be automatically inferred from the raw data.
- Sky color might be a nice feature to configure through the JSON as well.

### CODE REVIEW

**Review by RArbore — APPROVED** [review]
LGTM. scene_viewer segfaults on my machine on closing, but this doesn't really matter - would be nice to fix though.

**Comment by Jebbly** [comment]
> LGTM. scene_viewer segfaults on my machine on closing, but this doesn't really matter - would be nice to fix though.

Probably better to fix this, but I'm not able to reproduce this locally. Do you have any idea what's causing it? Can also dual boot to  Ubuntu 22.04 if it's a Linux thing

**Comment by RArbore** [comment]
The segfault occurs when trying to unmap the chunk download buffer. On my machine, it's happening somewhere in the nvidia userspace driver, so not easy to debug unfortunately.

**Comment by Jebbly** [comment]
> The segfault occurs when trying to unmap the chunk download buffer. On my machine, it's happening somewhere in the nvidia userspace driver, so not easy to debug unfortunately.

Okay, that doesn't sound especially related to this PR so will merge for now. Will test it out on Ubuntu later though.

**Pull request merged**
