### PR TITLE
Direct Light Sampling

### LINKED ISSUE #12: Implement Direct Light Sampling
## What

Right now, all the light from emissive voxels comes from indirect light sampling. It would be better to have some uniform buffer to keep track of which voxel chunks are emissive so that we can directly shoot rays at those chunks. Will probably be necessary for the Sponza scene.

### PR DESCRIPTION
**Pull request by Jebbly**
## What

Passes a list of emissive voxels to the ray generation shader, so that paths can directly sample lights. 

Not done yet, need to verify whether choosing 3 faces is enough or all 6 are required. Optimizations would be helpful, also need to double check if things are unbiased.

### CODE REVIEW

**Comment by RArbore** [comment]
Will review later tonight.

**Comment by Jebbly** [comment]
Fixed some issues that made the direct light sampling seem worse than it actually was. Looks pretty good, here's an example after a few frames of accumulation:
image

Will probably need to play around with some parameters to make Sponza look good, and would be nice to have control over the skylight intensity from the driver level. Looks like some fireflies appear after running image accumulation for too long - could be due to overflow or some divide by 0, need to look into it a bit further.

**Review by RArbore — CHANGES_REQUESTED** [review]
This looks really nice. Not a total blocker, but I think how we're handling super-luminant (alpha > 1) lights is not correct. I've attached a screenshot that demonstrates this. For this example, I've cranked up the alpha of the cube light to 50 to exaggerate the effect (will push code). Although the color of the light itself is correct, we see that the surrounding area has incorrect lighting. It should be very bright, but reflect the colors of the light (which are rainbow, not white). However, the light on the surface is mostly white. This is understandable in the sense that the light color * 50 and clipped equals white most of the time, but is undesirable. When the alpha is 50, this is true enough that you can see the effect on the cube light itself (the specs of white on the rainbow cube).
Screenshot from 2023-11-30 19-43-52

**Comment by Jebbly** [comment]
Pushed an ACES approximation which seems to map the luminance range slightly differently - I don't think the white is caused by the clipping but rather due to the voxel color components, but will need to investigate further.

**Pull request merged**
